# Generated by Django 4.2.3 on 2023-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tripadvisor',
            field=models.URLField(blank=True, null=True),
        ),
    ]
