# Generated by Django 4.2.3 on 2023-10-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_info_tripadvisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='facebook',
            new_name='map_url',
        ),
    ]
