# Generated by Django 4.2.3 on 2023-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
