# Generated by Django 4.2.3 on 2023-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_info_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
